### ISSUE TITLE
adminlt v2

### ISSUE THREAD

**Issue by Boco10** [dmstr/yii2-adminlte-asset#19]
Hello. 

I've just tried to install the v2 version of adminlte but the default page doesn't seems to be fine.

**Comment by Boco10** [comment]
Just to be more specific.

Installed it via composer.
Copied the files over to backend/views => Overwrite = yes
Opened backend/web in browser. Seems Something broken, i can see a a broken menu, but if i click any of them its render the v2 style and naviage to /backend/web/assets/77103d9/admin-lte/index.html which is working fine. Can you please have a look?

**Comment by schmunk42** [comment]
Sorry, my fault. I added a notice, that it's not ready.

**Comment by Boco10** [comment]
Do you have any eta ? Really want to start working with it, but kinda new to be able to solve that myself. Thanks.

**Comment by schmunk42** [comment]
asset bundle is fixed and here's an example layout for Phundament https://github.com/dmstr/yii2-adminlte-asset/blob/master/example-views/phundament/app/layouts/main.php

Should be quite easy to adopt it to the yii templates (if needed ;))

**Comment by kaynewilder** [comment]
Hi @schmunk42 . Like @Boco10 , I am also using the version 2 and just noticed a while ago the note that you added. I am using the basic template though. And my page is also not fine. Here it is:
![aaaaaaa](https://cloud.githubusercontent.com/assets/11188562/6405721/e9ee6f98-be61-11e4-8e02-0840f84007b5.JPG)

As you can see, the top bar does not seem to look fine. It's broken.
How do I fix this?

**Comment by schmunk42** [comment]
Here's how it looks for me with Phundament 4 (current dev-master), maybe double check your markup?

![bildschirmfoto 2015-02-27 um 06 27 31](https://cloud.githubusercontent.com/assets/649031/6407891/d1185258-be49-11e4-86b1-b88ee3e404d6.png)

**Comment by kaynewilder** [comment]
I made new basic template project to see if the problem is just with my current project. But unfortunately, I got the same problem, the top bar is still broken.

I installed version 2 with php composer.phar require dmstr/yii2-adminlte-asset "2.*@dev" and I didn't see any failure or what so ever upon installation.

And what do you mean by markup? Sorry I'm not used to those terms and I am also new to github.

**Comment by schmunk42** [comment]
Welcome ;)

Do you use Phundament 4, yii2-app-basic or yii2-app-advanced?
With markup I meant the layout (`views/layouts/main.php`) of your application or module.

This is the Phundament 4 layout from the screenshot above ... you may try starting with this
https://github.com/dmstr/yii2-adminlte-asset/blob/master/example-views/phundament/app/layouts/main.php

**Comment by kaynewilder** [comment]
I mentioned that I am using the basic app from yii. :)
I followed the customization steps here: https://github.com/dmstr/yii2-adminlte-asset

Look how awful the new yii basic project I just made:
Index page
![wew](https://cloud.githubusercontent.com/assets/11188562/6408252/9da68de4-be8b-11e4-97d6-fb5b6e5c6daf.JPG)
Login page
![wew2](https://cloud.githubusercontent.com/assets/11188562/6408253/9dbd2086-be8b-11e4-802b-7e1ba6c8f666.JPG)

**Comment by schmunk42** [comment]
Stick with v1 until it's fixed. `"2.*@dev"` indicates a development version btw.

**Comment by kaynewilder** [comment]
Yes it is. Was just wondering if version 2 already has a presentable layout. Thank you for your response!

**Comment by Boco10** [comment]
Thanks, i was able to solve it. :+1:

**Comment by schmunk42** [comment]
PRs always welcome!

**Comment by anas-shehadeh** [comment]
@Boco10 how you solve it ??

**Comment by DmitrySoloviyev** [comment]
really, how?

**Comment by schmunk42** [comment]
As mentioned above, you should start by adopting https://github.com/dmstr/yii2-adminlte-asset/blob/master/example-views/phundament/app/layouts/main.php

PRs welcome!

**Comment by schmunk42** [comment]
see https://github.com/dmstr/yii2-adminlte-asset/releases/tag/2.0.0-beta1
